TRAITS = [
    {"name": "Arcane Whiskers", "emoji": "✨", "desc": "+25 Magicka, +10% spell crit chance / −10 HP"},
    {"name": "Nine Lives", "emoji": "♾️", "desc": "Revive once per battle / −20 Stamina"},
    {"name": "Street Mouser", "emoji": "🐀", "desc": "+15% rat catch chance / −10 Magicka"},
    {"name": "Nocturnal Prowler", "emoji": "🌙", "desc": "Higher hit rate at night / −10% daylight damage"},
    {"name": "Arcane Fur", "emoji": "🧥", "desc": "Take less magic damage / −5 physical defense"},
    {"name": "Clawed Scholar", "emoji": "📜", "desc": "Extra XP from spells / −10 Stamina"},
    {"name": "Iron Fur", "emoji": "🪨", "desc": "+40 HP / −15 Magicka"},
    {"name": "Dreamhunter", "emoji": "💤", "desc": "+10% crit in dungeons / −5% catch chance"},
    {"name": "Sun-Touched", "emoji": "☀️", "desc": "+10% daylight regen / −10% night power"},
    {"name": "Feral Grace", "emoji": "🐾", "desc": "+10% evasion / −10% magic resist"},
    {"name": "Lone Pouncer", "emoji": "⚔️", "desc": "+15% damage solo / −15% defense in party"},
    {"name": "Spirit-Tethered", "emoji": "🔮", "desc": "+5 mag regen / −5 stamina regen"},
    {"name": "Dwemer-Blooded", "emoji": "⚙️", "desc": "Immune to poison / −10% healing received"},
    {"name": "Ayleid Grace", "emoji": "💎", "desc": "+5% spell speed / −10% physical defense"},
    {"name": "Plague Hunter", "emoji": "☣️", "desc": "Extra damage to infected rats / −5 HP regen"},
    {"name": "Silver Paws", "emoji": "💰", "desc": "Find rare loot +10% / −10% XP gain"},
    {"name": "Mirthful Tail", "emoji": "🎭", "desc": "+5 social bonus / −5 combat focus"},
    {"name": "Brittle Bones", "emoji": "🦴", "desc": "+15 mag power / −30 HP"},
    {"name": "Burrow Dweller", "emoji": "🕳️", "desc": "+10 rat spawn detection / −5 daylight vision"},
    {"name": "Wanderclaw", "emoji": "🌍", "desc": "+5% XP per new area / −10% defense vs elites"},
]
